### ISSUE TITLE
Ore-Readout 1.3.0 crashes on 1.17

### ISSUE THREAD

**Issue by FlyGuyGo** [yitzy299/Ore-Readout#2]
When using Ore-Readout 1.3.0 on a Fabric Minecraft 1.17 server with only Fabric API 0.34.9 installed, it will crash.

`[20:19:36] [main/INFO]: Loading for game Minecraft 1.17
[20:19:37] [main/INFO]: [FabricLoader] Loading 48 mods: fabric-networking-blockentity-v0@0.2.11+a02b4463d5, fabric-screen-handler-api-v1@1.1.8+a02b4463d5, minecraft@1.17, fabric-renderer-api-v1@0.4.2+a02b4463d5, fabric-keybindings-v0@0.2.2+36b77c3ed5, fabric-command-api-v1@1.1.1+a02b4463d5, fabricloader@0.11.3, fabric-screen-api-v1@1.0.3+b7ab6121d5, fabric-tool-attribute-api-v1@1.2.12+b7ab6121d5, fabric-renderer-indigo@0.4.8+a02b4463d5, fabric-structure-api-v1@1.1.10+be9da310d5, fabric-containers-v0@0.1.12+a02b4463d5, fabric-dimensions-v1@2.0.10+a02b4463d5, fabric-object-builder-api-v1@1.10.9+b7ab6121d5, java@16, fabric-events-interaction-v0@0.4.8+a02b4463d5, fabric-crash-report-info-v1@0.1.5+be9da310d5, fabric-item-api-v1@1.2.4+a02b4463d5, ore-readout@1.3.0, fabric-game-rule-api-v1@1.0.6+a02b4463d5, fabric-entity-events-v1@1.1.0+a02b4463d5, fabric-api-base@0.3.0+a02b4463d5, fabric-rendering-v0@1.1.2+92519afad5, fabric-key-binding-api-v1@1.0.4+a02b4463d5, fabric-rendering-v1@1.6.0+a02b4463d5, fabric-rendering-data-attachment-v1@0.1.5+a02b4463d5, fabric-resource-loader-v0@0.4.7+b7ab6121d5, fabric-textures-v0@1.0.6+a02b4463d5, fabric-content-registries-v0@0.2.2+a02b4463d5, fabric-tag-extensions-v0@1.1.4+a02b4463d5, fabric-biome-api-v1@3.1.11+9e521e13d5, fabric-rendering-fluids-v1@0.1.13+a02b4463d5, fabric-commands-v0@0.2.2+92519afad5, fabric-registry-sync-v0@0.7.9+a02b4463d5, fabric-blockrenderlayer-v1@1.1.5+a02b4463d5, fabric-lifecycle-events-v1@1.4.4+a02b4463d5, fabric-mining-levels-v0@0.1.3+92519afad5, fabric-renderer-registries-v1@3.2.0+a02b4463d5, fabric-networking-api-v1@1.0.11+b7ab6121d5, fabric-events-lifecycle-v0@0.2.1+92519afad5, fabric-loot-tables-v1@1.0.4+a02b4463d5, fabric@0.34.9+1.17, fabric-item-groups-v0@0.2.10+b7ab6121d5, fabric-models-v0@0.3.0+a02b4463d5, fabric-particles-v1@0.2.4+a02b4463d5, fabric-object-builders-v0@0.7.3+a02b4463d5, fabric-networking-v0@0.3.2+92519afad5, fabric-api-lookup-api-v1@1.0.2+a02b4463d5
[20:19:37] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.2 Source=file:/E:/1.17%20Data%20Pack%20Test%20Server/fabric-server-launch.jar Service=Knot/Fabric Env=SERVER
[20:19:37] [main/WARN]: The requested compatibility level JAVA_16 is higher than the level supported by the active subsystem 'Knot/Fabric' which supports JAVA_14. This is not a supported configuration and instability may occur.
[20:19:37] [main/INFO]: Compatibility level set to JAVA_16
[20:19:37] [main/WARN]: @Mixin target net/minecraft/class_2474$class_5124 is public in fabric-tag-extensions-v0.mixins.json:MixinObjectBuilder and should be specified in value
[20:19:40] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:server.WorldChunkMixin::handler$zzh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.`

The crash:

`[20:19:40] [main/FATAL]: Failed to start the minecraft server
java.lang.RuntimeException: Could not execute entrypoint stage 'server' due to errors, provided by 'ore-readout'!
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-launch.jar:?]
        at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-launch.jar:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
        at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-launch.jar:?]
        at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-launch.jar:?]
Caused by: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'server' provided by 'ore-readout'
        at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:186) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more
Caused by: net.fabricmc.loader.api.LanguageAdapterException: Class com.github.yitzy299.orereadout.OreReadout cannot be cast to net.fabricmc.api.DedicatedServerModInitializer!
        at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:59) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric-server-launch.jar:?]
        at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-launch.jar:?]
        ... 17 more`

**Comment by yitzy299** [comment]
Grab the latest actions build

**Comment by FlyGuyGo** [comment]
> Grab the latest actions build

Do you know where I can find this? I am not familiar with actions.

**Comment by yitzy299** [comment]
https://github.com/yitzy299/Ore-Readout/actions/runs/924267902

**Comment by FlyGuyGo** [comment]
> https://github.com/yitzy299/Ore-Readout/actions/runs/924267902

Forgive me, I am a novice when it comes to Github and coding. Does the action build require me to compile the plugin myself?

**Comment by yitzy299** [comment]
No, you download the zip and take the jar
