### ISSUE TITLE
crashing 1.17 fabric server

### ISSUE THREAD

**Issue by jakey1995abc** [yitzy299/Ore-Readout#3]
[14.06 16:30:27] [Server] [main/FATAL]: Failed to start the minecraft server
[14.06 16:30:27] [Server] java.lang.RuntimeExceptionCould not execute entrypoint stage 'server' due to errors, provided by 'ore-readout'!
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:53) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke(EntrypointUtils.java:36) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointServer.start(EntrypointServer.java:33) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.minecraft.server.Main.main(Main.java:97) [intermediary-server.jar:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[14.06 16:30:27] [Server] 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.game.MinecraftGameProvider.launch(MinecraftGameProvider.java:226) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.launch.knot.Knot.launch(Knot.java:146) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.launch.knot.KnotServer.main(KnotServer.java:28) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:78) ~[?:?]
[14.06 16:30:27] [Server] 	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
[14.06 16:30:27] [Server] 	at java.lang.reflect.Method.invoke(Method.java:567) ~[?:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.launch.server.FabricServerLauncher.launch(FabricServerLauncher.java:62) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.launch.server.FabricServerLauncher.setup(FabricServerLauncher.java:106) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:50) [fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] Caused bynet.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'server' provided by 'ore-readout'
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:186) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	... more
[14.06 16:30:27] [Server] Caused bynet.fabricmc.loader.api.LanguageAdapterException: Class com.github.yitzy299.orereadout.OreReadout cannot be cast to net.fabricmc.api.DedicatedServerModInitializer!
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:59) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.EntrypointStorage$NewEntry.create(EntrypointStorage.java:112) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:99) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.EntrypointStorage.lambda$getEntrypointContainers$1(EntrypointStorage.java:184) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:37) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	at net.fabricmc.loader.entrypoint.minecraft.hooks.EntrypointUtils.invoke0(EntrypointUtils.java:50) ~[fabric-server-1.17-0113.jar:?]
[14.06 16:30:27] [Server] 	... more

**Comment by yitzy299** [comment]
See #2
